print ('')
print ('                 |--------------------| ')
print ('                 |Soma de dois numeros| ')
print ('                 |--------------------| ')
print ('')
print ('Coletando dados')
print ('---------------')
a = float (input ('Entre com o primeiro valor: '))
print ('')
b = float (input ('Entre com o segundo  valor: '))
print ('')
print ('Somando os valores inseridos')
r = a + b
print ('O resultado é: ',r)
print ('')
print ('|---------------|')
print ('|FIM DO PROCESSO|')
print ('|---------------|')
